# -*- coding: utf-8 -*-
"""DeepLearning_PredictingNewData 12.11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qA9Q4U9o4C-zkOS9W2E5R-6vVzNQ4LZ-

# Predicting on new data

## Import the relevant libraries
"""

import numpy as np
import tensorflow as tf
import pickle

"""## Load the scaler and the model"""

from google.colab import drive
drive.mount('/content/drive')

#Load scaler and model
scaler_deep_learning = pickle.load(open('/content/drive/My Drive/Customer Analytics/scaler_deep_learning.pickle', 'rb'))
model = tf.keras.models.load_model('/content/drive/My Drive/Customer Analytics/audiobooks_model.h5')

"""## Load the new data"""

raw_data = np.loadtxt('/content/drive/My Drive/Customer Analytics/New_Audiobooks_Data.csv', delimiter = ',')
new_data_inputs = raw_data[:,1:]

"""## Predict the probability of a customer to convert"""

#Scale the data as the sameway did for training dataset.
new_data_inputs_scaled = scaler_deep_learning.transform(new_data_inputs)

#Predict the probability of converting
model.predict(new_data_inputs_scaled)[:,1].round(2)

#Utilize argmax funtion to get better results
np.argmax(model.predict(new_data_inputs_scaled),1)